#!/system/bin/sh

who=`su -c whoami`
if [ "$who" != "root" ]; then
        root=no
else
        root=yes                                                            
fi

if [ "$root" = "yes" ]; then
        su -c setprop persist.vendor.camera.HAL3.enabled 1
        su -c setprop persist.camera.HAL3.enabled 1
        su -c stop vendor.camera-provider-2-4
        su -c stop cameraserver
        su -c start vendor.camera-provider-2-4
        su -c start cameraserver
	echo "done"
else
        echo "Root access not found"
	exit
fi
