#!/system/bin/sh

RED="\033[1;31m" # For errors / warnings
GREEN="\033[1;32m" # For info
NC="\033[0m" # reset color

who=`su -c whoami`
if [ "$who" != "root" ]; then
        root=no
else
        root=yes                                                            
fi

if [ "$root" = "yes" ]; then
        su -c setprop persist.vendor.camera.HAL3.enabled 1
        su -c setprop persist.camera.HAL3.enabled 1
        su -c stop vendor.camera-provider-2-4
        su -c stop cameraserver
        su -c start vendor.camera-provider-2-4
        su -c start cameraserver
	echo -e "${GREEN}done${NC}"
else
        echo -e "${RED}Root access not found${NC}"
	exit
fi
